"""
Pydantic Models for Structured Outputs

Defines the data models that agents must return for type-safe,
validated responses from the LLM.
"""

from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime
from enum import Enum


class TaskType(str, Enum):
    """Types of tasks that can be processed."""
    EMAIL = "email"
    SOCIAL = "social"
    FINANCE = "finance"
    GENERAL = "general"
    UNKNOWN = "unknown"


class AgentType(str, Enum):
    """Specialized agent types."""
    TRIAGE = "triage"
    EMAIL = "email"
    SOCIAL = "social"
    FINANCE = "finance"


class ConfidenceLevel(str, Enum):
    """Confidence levels for agent outputs."""
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class RiskLevel(str, Enum):
    """Risk levels for actions."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ============================================================================
# Triage Models
# ============================================================================

class TriageDecision(BaseModel):
    """Decision from TriageAgent about which specialist should handle a task."""

    task_type: TaskType = Field(
        description="The type of task this is"
    )
    target_agent: AgentType = Field(
        description="Which specialist agent should handle this task"
    )
    confidence: ConfidenceLevel = Field(
        description="How confident the triage agent is in this decision"
    )
    reasoning: str = Field(
        description="Explanation of why this task was routed to this agent"
    )
    requires_human_input: bool = Field(
        default=False,
        description="Whether the task is ambiguous and requires human clarification"
    )
    questions_for_human: list[str] = Field(
        default_factory=list,
        description="Questions to ask the human if clarification is needed"
    )


# ============================================================================
# Email Models
# ============================================================================

class EmailDraft(BaseModel):
    """Draft email response generated by EmailAgent."""

    to: str = Field(
        description="Recipient email address"
    )
    subject: str = Field(
        description="Email subject line"
    )
    body: str = Field(
        description="Email body content (plain text or markdown)"
    )
    confidence: ConfidenceLevel = Field(
        description="How confident the agent is in this draft"
    )
    needs_approval: bool = Field(
        default=True,
        description="Whether this email requires human review before sending (always true)"
    )
    tone: str = Field(
        default="professional",
        description="The tone of the email (professional, friendly, formal, casual)"
    )
    suggested_changes: list[str] = Field(
        default_factory=list,
        description="Any suggested edits or improvements the human should consider"
    )
    missing_info: list[str] = Field(
        default_factory=list,
        description="Information that was missing or unclear in the original email"
    )


# ============================================================================
# Social Media Models
# ============================================================================

class SocialPlatform(str, Enum):
    """Social media platforms."""
    LINKEDIN = "linkedin"
    TWITTER = "twitter"
    FACEBOOK = "facebook"
    INSTAGRAM = "instagram"


class SocialPost(BaseModel):
    """Social media post draft generated by SocialAgent."""

    platform: SocialPlatform = Field(
        description="Which platform this post is for"
    )
    content: str = Field(
        description="The post content (handles platform character limits)"
    )
    hashtags: list[str] = Field(
        default_factory=list,
        description="Relevant hashtags for the post"
    )
    confidence: ConfidenceLevel = Field(
        description="How confident the agent is in this draft"
    )
    needs_approval: bool = Field(
        default=True,
        description="Whether this post requires human review before posting (always true)"
    )
    post_type: Literal["post", "reply", "comment"] = Field(
        default="post",
        description="Type of social content"
    )
    scheduled_time: Optional[datetime] = Field(
        default=None,
        description="Suggested time to post (if scheduling is available)"
    )
    character_count: int = Field(
        default=0,
        description="Character count of the content"
    )

    def model_post_init(self, __context: any) -> None:
        """Calculate character count after initialization."""
        self.character_count = len(self.content)


# ============================================================================
# Finance Models
# ============================================================================

class FinanceActionType(str, Enum):
    """Types of financial actions."""
    CREATE_INVOICE = "create_invoice"
    ANALYZE_TRANSACTION = "analyze_transaction"
    PAYMENT_SUMMARY = "payment_summary"
    FLAG_UNUSUAL = "flag_unusual"
    REVENUE_INSIGHT = "revenue_insight"


class FinanceAction(BaseModel):
    """Financial action recommendation generated by FinanceAgent."""

    action_type: FinanceActionType = Field(
        description="The type of financial action to take"
    )
    description: str = Field(
        description="Human-readable description of the action"
    )
    amount: Optional[float] = Field(
        default=None,
        description="Monetary amount involved (if applicable)"
    )
    currency: str = Field(
        default="USD",
        description="Currency code"
    )
    risk_level: RiskLevel = Field(
        default=RiskLevel.LOW,
        description="Risk level of this action"
    )
    confidence: ConfidenceLevel = Field(
        description="How confident the agent is in this recommendation"
    )
    needs_approval: bool = Field(
        default=True,
        description="Whether this action requires human approval (always true for finance)"
    )
    reasoning: str = Field(
        description="Explanation of why this action is recommended"
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Any warnings or concerns the human should be aware of"
    )
    suggested_data: dict = Field(
        default_factory=dict,
        description="Structured data for the action (e.g., invoice line items)"
    )


# ============================================================================
# Generic Response Model
# ============================================================================

class AgentResponse(BaseModel):
    """Generic agent response wrapper for unknown/unhandled tasks."""

    content: str = Field(
        description="The agent's response or explanation"
    )
    task_type: TaskType = Field(
        description="The type of task that was processed"
    )
    confidence: ConfidenceLevel = Field(
        default=ConfidenceLevel.MEDIUM,
        description="Confidence level in the response"
    )
    needs_human_review: bool = Field(
        default=True,
        description="Whether this response requires human review"
    )
    next_steps: list[str] = Field(
        default_factory=list,
        description="Suggested next steps"
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if the task could not be processed"
    )
